format = "$username$hostname$directory$line_break$character"
add_newline = false
right_format = "$cmd_duration"

[line_break]
disabled = false

[package]
disabled = true

[username]
style_user = "bold fg:#FFFFFF"
style_root = "bold fg:#FFFFFF"
format = "[・]($style)[ $user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "[・](bold fg:#FFFFFF)[ $hostname](bold fg:#FFFFFF)[・](bold fg:#FFFFFF)"
trim_at = ".companyname.com"
disabled = false

[directory]
home_symbol = " "
read_only = "  "
style = "bold fg:#FFFFFF"
truncation_length = 2
truncation_symbol = "./"
format = "[$path]($style)[・]($style)"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = "󰝚 "
"Playlists" = "󰲸 "
"Pictures" = " "
"Games" = " "
"Videos" = " "
"Desktop" = " "
"Books" = " "
"Android" = "󰀲 "

[cmd_duration]
min_time = 0;
format = "[・](bold fg:#FFFFFF)[󰄉 time:$duration](bold fg:#FFFFFF)[・](bold fg:#FFFFFF)";

[character]
error_symbol = "[  ╰](bold fg:#FFFFFF)[x](fg:#FFFFFF)[](bold fg:#FFFFFF)"
success_symbol = "[  ╰](bold fg:#FFFFFF)[∙](bold fg:#FFFFFF)[](bold fg:#FFFFFF)"

